# Generated by Django 2.2 on 2019-07-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_category', models.CharField(max_length=200)),
                ('course_summary', models.CharField(max_length=200)),
                ('course_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Course Categories',
            },
        ),
        migrations.CreateModel(
            name='courses_series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('course_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.course_category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Course Series',
            },
        ),
        migrations.CreateModel(
            name='master_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
                ('course_duration', models.IntegerField(default=1)),
                ('course_contents', models.TextField(default=1)),
                ('course_slug', models.CharField(default=1, max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('course_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.courses_series', verbose_name='Series')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
